# Display
TARGET_DISPLAY_USE_RETIRE_FENCE := true

# Adreno driver
OVERRIDE_RS_DRIVER := libRSDriver_adreno.so

# Ion
TARGET_USES_C2D_COMPOSITION := true
TARGET_USES_ION := true

# EGL
MAX_EGL_CACHE_KEY_SIZE := 12*1024
MAX_EGL_CACHE_SIZE := 2048*1024
